version: '3.8'

services:
  barkeep:
    image: barkeep
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      BOT_TOKEN: /var/run/secrets/discord_bot_token
    secrets:
      - BOT_TOKEN
      
secrets:
  BOT_TOKEN:
    file: ./configs/BOT_TOKEN